export const RESET = 'RESET';
export const LOGOUT = 'LOGOUT';

export const FETCH_TOKEN = 'FETCH_TOKEN';
export const TOKEN = 'TOKEN';
export const TOKEN_FAILED = 'TOKEN_FAILED';

//notification related
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const SET_USER_ID = 'export const';



export const SAVE_BOOKING = 'SAVE_BOOKING';
export const SAVE_BOOKING_RECEIVED = 'SAVE_BOOKING_RECEIVED';
export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const BOOKINGS_RECEIVED = 'FETCH_BOOKINGS_RECEIVED';
export const BOOKINGS_REQUEST_FAILED = 'BOOKINGS_REQUEST_FAILED';
export const FETCH_BOOKING = 'FETCH_BOOKING';
export const FETCH_BOOKING_RECEIVED = 'FETCH_BOOKING_RECEIVED';
export const FETCH_BOOKING_FAILED = 'FETCH_BOOKING_FAILED';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const UPDATE_BOOKING_RECEIVED = 'UPDATE_BOOKING_RECEIVED';
export const UPDATE_BOOKING_FAILED = 'UPDATE_BOOKING_FAILED';

export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_RECEIVED = 'DELETE_BOOKING_RECEIVED';
export const DELETE_FAILED = 'DELETE_FAILED';
export const SAVE_FAILED = 'SAVE_FAILED';

export const ROOM_DETAILS_RECEIVED = 'ROOM_DETAILS_RECEIVED';
export const ROOM_DETAILS_FAILED = 'ROOM_DETAILS_FAILED';
export const FETCH_ROOM_DETAILS = 'FETCH_ROOM_DETAILS';

export const FETCH_HOTEL_RECEIVED = 'FETCH_HOTEL_RECEIVED';
export const FETCH_HOTEL_FAILED = 'FETCH_HOTEL_FAILED';
export const UPDATE_HOTEL_RECEIVED = 'UPDATE_HOTEL_RECEIVED';
export const UPDATE_HOTEL_FAILED = 'UPDATE_HOTEL_FAILED';
export const FETCH_HOTEL = 'FETCH_HOTEL';
export const UPDATE_HOTEL = 'UPDATE_HOTEL';


export const SAVE_ROOMTYPE = 'SAVE_ROOMTYPE';
export const SAVE_ROOMTYPE_RECEIVED = 'SAVE_ROOMTYPE_RECEIVED';
export const FETCH_ROOMTYPES = 'FETCH_ROOMTYPES';
export const ROOMTYPES_RECEIVED = 'ROOMTYPES_RECEIVED';
export const ROOMTYPES_REQUEST_FAILED = 'ROOMTYPES_REQUEST_FAILED';
export const FETCH_ROOMTYPE = 'FETCH_ROOMTYPE';
export const FETCH_ROOMTYPE_RECEIVED = 'FETCH_ROOMTYPE_RECEIVED';
export const FETCH_ROOMTYPE_FAILED = 'FETCH_ROOMTYPE_FAILED';
export const UPDATE_ROOMTYPE = 'UPDATE_ROOMTYPE';
export const UPDATE_ROOMTYPE_RECEIVED = 'UPDATE_ROOMTYPE_RECEIVED';
export const UPDATE_ROOMTYPE_FAILED = 'UPDATE_ROOMTYPE_FAILED';

export const DELETE_ROOMTYPE = 'DELETE_ROOMTYPE';
export const DELETE_ROOMTYPE_RECEIVED = 'DELETE_ROOMTYPE_RECEIVED';



export const SAVE_ROOM = 'SAVE_ROOM';
export const SAVE_ROOM_RECEIVED = 'SAVE_ROOM_RECEIVED';
export const FETCH_ROOMS = 'FETCH_ROOMS';
export const ROOMS_RECEIVED = 'ROOMS_RECEIVED';
export const ROOMS_REQUEST_FAILED = 'ROOMS_REQUEST_FAILED';
export const FETCH_ROOM = 'FETCH_ROOM';
export const FETCH_ROOM_RECEIVED = 'FETCH_ROOM_RECEIVED';
export const FETCH_ROOM_FAILED = 'FETCH_ROOM_FAILED';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_ROOM_RECEIVED = 'UPDATE_ROOM_RECEIVED';
export const UPDATE_ROOM_FAILED = 'UPDATE_ROOM_FAILED';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_RECEIVED = 'DELETE_ROOM_RECEIVED';

export const ROOM_TYPES_RECEIVED = 'ROOM_TYPES_RECEIVED';
export const ROOM_TYPES_FAILED ='ROOM_TYPES_FAILED';



export const SAVE_PRICELIST = 'SAVE_PRICELIST';
export const SAVE_PRICELIST_RECEIVED = 'SAVE_PRICELIST_RECEIVED';
export const FETCH_PRICELISTS = 'FETCH_PRICELISTS';
export const PRICELISTS_RECEIVED = 'PRICELISTS_RECEIVED';
export const PRICELISTS_REQUEST_FAILED = 'PRICELISTS_REQUEST_FAILED';
export const FETCH_PRICELIST = 'FETCH_PRICELIST';
export const FETCH_PRICELIST_RECEIVED = 'FETCH_PRICELIST_RECEIVED';
export const FETCH_PRICELIST_FAILED = 'FETCH_PRICELIST_FAILED';
export const UPDATE_PRICELIST = 'UPDATE_PRICELIST';
export const UPDATE_PRICELIST_RECEIVED = 'UPDATE_PRICELIST_RECEIVED';
export const UPDATE_PRICELIST_FAILED = 'UPDATE_PRICELIST_FAILED';

export const DELETE_PRICELIST = 'DELETE_PRICELIST';
export const DELETE_PRICELIST_RECEIVED = 'DELETE_PRICELIST_RECEIVED';

export const PRICELIST_TYPES_RECEIVED = 'PRICELIST_TYPES_RECEIVED';
export const PRICELIST_TYPES_FAILED ='PRICELIST_TYPES_FAILED';


export const BOOKING_DETAILS_RECEIVED = 'BOOKING_DETAILS_RECEIVED';
export const BOOKING_DETAILS_FAILED = 'BOOKING_DETAILS_FAILED';
export const FETCH_BOOKING_DETAILS = 'FETCH_BOOKING_DETAILS';


export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_USER = 'REGISTER_USER';
